#!/bin/bash
#SBATCH --job-name=new-loss
#SBATCH --partition=cse-gpu-all
#SBATCH --nodelist=cse-node010
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --gres=gpu:2
#SBATCH --mem=16G
#SBATCH --time=48:00:00

# Load the Anaconda module
module load anaconda3/2024.02-1

# Activate the Conda environment
source activate csr-env

# # Run for Art (Pr, Cl, Rw → Ar) using srun
# srun --partition=cse-gpu-all --nodelist=dgx-a100-01 --gres=gpu:1 python3 main.py --name 'office31' --src 'webcam' 'dslr' --tar 'amazon' --batch-size 32 --warmup-steps 0 --student-wait-steps 0 --wait_step 100 --bottleneck 'linear' --total-steps 5001 --num-classes 31 --tar_weight 1.0 --tar_threshold 0.9 --tar_alignment_weight 0.5 --src_tar_weight 0.0 --consis_tar --consis_weight 0.0 --ext_weight 0.0 --res_weight 0.01 --align_mode 1 --ext_mode 0 --seed 8 --amp --use_weight_pred --weight_tau 1.0 --port 15339 --grad-clip 10.0 --ot_alpha 1.0 --ot_beta 0.5 --ot_gamma 0.5 --word2vec_path 'GoogleNews-vectors-negative300.bin' > ./office31_ot_amazon.log 2>&1

# srun --partition=cse-gpu-all --nodelist=dgx-a100-01 --gres=gpu:1 python3 main.py --name 'office31' --src 'amazon' 'dslr' --tar 'webcam' --batch-size 32 --warmup-steps 0 --student-wait-steps 0 --wait_step 100 --bottleneck 'linear' --total-steps 5001 --num-classes 31 --tar_weight 1.0 --tar_threshold 0.9 --tar_alignment_weight 0.5 --src_tar_weight 0.0 --consis_tar --consis_weight 0.0 --ext_weight 0.0 --res_weight 0.01 --align_mode 1 --ext_mode 0 --seed 8 --amp --use_weight_pred --weight_tau 1.0 --port 15339 --grad-clip 10.0 --ot_alpha 1.0 --ot_beta 0.5 --ot_gamma 0.5 --word2vec_path 'GoogleNews-vectors-negative300.bin' > ./office31_ot_webcam.log 2>&1

# srun --partition=cse-gpu-all --nodelist=dgx-a100-01 --gres=gpu:1 python3 main.py --name 'office31' --src 'webcam' 'amazon' --tar 'dslr' --batch-size 32 --warmup-steps 0 --student-wait-steps 0 --wait_step 100 --bottleneck 'linear' --total-steps 5001 --num-classes 31 --tar_weight 1.0 --tar_threshold 0.9 --tar_alignment_weight 0.5 --src_tar_weight 0.0 --consis_tar --consis_weight 0.0 --ext_weight 0.0 --res_weight 0.01 --align_mode 1 --ext_mode 0 --seed 8 --amp --use_weight_pred --weight_tau 1.0 --port 15339 --grad-clip 10.0 --ot_alpha 1.0 --ot_beta 0.5 --ot_gamma 0.5 --word2vec_path 'GoogleNews-vectors-negative300.bin' > ./office31_ot_dslr.log 2>&1

# srun --partition=cse-gpu-all --nodelist=cse-node009 --gres=gpu:1 python3 main.py --name 'officehome' --src 'webcam' 'amazon' --tar 'dslr' --batch-size 32 --warmup-steps 0 --student-wait-steps 0 --wait_step 100 --bottleneck 'linear' --total-steps 5001 --num-classes 31 --tar_weight 1.0 --tar_threshold 0.9 --tar_alignment_weight 0.5 --src_tar_weight 0.0 --consis_tar --consis_weight 0.0 --ext_weight 0.0 --res_weight 0.01 --align_mode 1 --ext_mode 0 --seed 8 --amp --use_weight_pred --weight_tau 1.0 --port 15339 --grad-clip 10.0 --ot_alpha 1.0 --ot_beta 0.5 --ot_gamma 0.5 --word2vec_path 'GoogleNews-vectors-negative300.bin' > ./office31_ot_dslr.log 2>&1

# srun --partition=cse-gpu-all --nodelist=cse-node009 --gres=gpu:1 python3 main.py --name 'officehome' --src 'Art' 'dslr' --tar 'webcam' --batch-size 32 --warmup-steps 0 --student-wait-steps 0 --wait_step 100 --bottleneck 'linear' --total-steps 5001 --num-classes 31 --tar_weight 1.0 --tar_threshold 0.9 --tar_alignment_weight 0.5 --src_tar_weight 0.0 --consis_tar --consis_weight 0.0 --ext_weight 0.0 --res_weight 0.01 --align_mode 1 --ext_mode 0 --seed 8 --amp --use_weight_pred --weight_tau 1.0 --port 15339 --grad-clip 10.0 --ot_alpha 1.0 --ot_beta 0.5 --ot_gamma 0.5 --word2vec_path 'GoogleNews-vectors-negative300.bin' > ./office31_ot_webcam.log 2>&1

# srun --partition=cse-gpu-all --nodelist=dgx-v100-01 --gres=gpu:1 python3 main.py --name 'officehome' --src 'Art' 'Clipart' 'Product' --tar 'Real_World' --batch-size 32 --warmup-steps 0 --student-wait-steps 0 --wait_step 100 --bottleneck 'linear' --total-steps 10001 --num-classes 65 --tar_weight 1.5 --tar_threshold 0.9 --tar_alignment_weight 0.5 --src_tar_weight 0.0 --consis_tar --consis_weight 0.0 --ext_weight 0.0 --res_weight 0.01 --align_mode 1 --ext_mode 0 --seed 8 --amp --use_weight_pred --weight_tau 1.0 --port 15367 --grad-clip 10.0 --ot_alpha 1.0 --ot_beta 0.5 --ot_gamma 0.5 --word2vec_path 'GoogleNews-vectors-negative300.bin' 2>&1 | tee ./officehome_ot_realworld.log 

# srun --partition=cse-gpu-all --nodelist=dgx-a100-01 --gres=gpu:1 python3 main.py --name 'officehome' --src 'Product' 'Clipart' 'Real_World' --tar 'Art' --batch-size 32 --warmup-steps 0 --student-wait-steps 0 --wait_step 100 --bottleneck 'linear' --total-steps 10001 --num-classes 65 --tar_weight 1.5 --tar_threshold 0.9 --tar_alignment_weight 0.5 --src_tar_weight 0.0 --consis_tar --consis_weight 0.0 --ext_weight 0.0 --res_weight 0.01 --align_mode 1 --ext_mode 0 --seed 8 --amp --use_weight_pred --weight_tau 1.0 --port 15360 --grad-clip 10.0 --ot_alpha 1.0 --ot_beta 0.5 --ot_gamma 0.5 --word2vec_path 'GoogleNews-vectors-negative300.bin' 2>&1 | tee ./officehome_ot_art.log

# srun --partition=cse-gpu-all --nodelist=dgx-a100-01 --gres=gpu:1 python3 main.py --name 'officehome' --src 'Art' 'Product' 'Real_World' --tar 'Clipart' --batch-size 32 --warmup-steps 0 --student-wait-steps 0 --wait_step 100 --bottleneck 'linear' --total-steps 10001 --num-classes 65 --tar_weight 1.5 --tar_threshold 0.9 --tar_alignment_weight 0.5 --src_tar_weight 0.0 --consis_tar --consis_weight 0.0 --ext_weight 0.0 --res_weight 0.01 --align_mode 1 --ext_mode 0 --seed 8 --amp --use_weight_pred --weight_tau 1.0 --port 15361 --grad-clip 10.0 --ot_alpha 1.0 --ot_beta 0.5 --ot_gamma 0.5 --word2vec_path 'GoogleNews-vectors-negative300.bin' 2>&1 | tee ./officehome_ot_clipart.log

# srun --partition=cse-gpu-all --nodelist=dgx-v100-01 --gres=gpu:2 python3 main.py --name 'DomainNet' --src 'painting' 'infograph' 'real' 'clipart' 'sketch' --tar 'quickdraw'  --batch-size 32 --backbone 'resnet101' --warmup-steps 0 --student-wait-steps 0 --eval-step 750 --wait_step 4000 --bottleneck 'linear' --total-steps 30001 --num-classes 345 --tar_weight 1.0 --tar_threshold 0.6 --tar_alignment_weight 0.7 --src_tar_weight 0.0 --consis_tar --box_warm_iter 1000 --bt 0.1 --consis_weight 0.0 --ext_weight 0.0 --res_weight 0.01 --align_mode 1 --ext_mode 0 --seed 8 --amp --use_weight_pred --weight_tau 1.0 --port 15611 --ot_alpha 1.0 --ot_beta 0.5 --ot_gamma 0.5 --word2vec_path 'GoogleNews-vectors-negative300.bin' 2>&1 | tee ./domainnet_ot_quickdraw.log

# srun --partition=cse-gpu-all --nodelist=dgx-v100-01 --gres=gpu:2 python3 main.py --name 'DomainNet' --src 'quickdraw' 'infograph' 'painting' 'real' 'clipart' --tar 'sketch'  --batch-size 32 --backbone 'resnet101' --warmup-steps 0 --student-wait-steps 0 --eval-step 750 --wait_step 1500 --bottleneck 'linear' --total-steps 40001 --num-classes 345 --tar_weight 1.0 --tar_threshold 0.6 --tar_alignment_weight 0.7 --src_tar_weight 0.0 --consis_tar --box_warm_iter 1000 --bt 0.1 --consis_weight 0.0 --ext_weight 0.0 --res_weight 0.01 --align_mode 1 --ext_mode 0 --seed 8 --amp --use_weight_pred --weight_tau 1.0  --port 15688 --ot_alpha 1.0 --ot_beta 0.5 --ot_gamma 0.5 --word2vec_path 'GoogleNews-vectors-negative300.bin' 2>&1 | tee ./domainnet_ot_sketch.log

# srun --partition=cse-gpu-all --nodelist=dgx-v100-01 --gres=gpu:2 python3 main.py --name 'DomainNet' --src 'quickdraw' 'infograph' 'painting' 'real' 'sketch' --tar 'clipart'  --batch-size 32 --backbone 'resnet101' --warmup-steps 0 --student-wait-steps 0 --eval-step 750 --wait_step 1500 --bottleneck 'linear' --total-steps 40001 --num-classes 345 --tar_weight 1.0 --tar_threshold 0.6 --tar_alignment_weight 0.7 --src_tar_weight 0.0 --consis_tar --box_warm_iter 1000 --bt 0.1 --consis_weight 0.0 --ext_weight 0.0 --res_weight 0.01 --align_mode 1 --ext_mode 0 --seed 8 --amp --use_weight_pred --weight_tau 1.0  --port 15655 --ot_alpha 1.0 --ot_beta 0.5 --ot_gamma 0.5 --word2vec_path 'GoogleNews-vectors-negative300.bin' 2>&1 | tee ./domainnet_ot_clipart.log

# srun --partition=cse-gpu-all --nodelist=dgx-v100-01 --gres=gpu:2 python3 main.py --name 'DomainNet' --src 'quickdraw' 'infograph' 'painting' 'sketch' 'clipart' --tar 'real'  --batch-size 32 --backbone 'resnet101' --warmup-steps 0 --student-wait-steps 0 --eval-step 750 --wait_step 1500 --bottleneck 'linear' --total-steps 50001 --num-classes 345 --tar_weight 1.0 --tar_threshold 0.6 --tar_alignment_weight 0.7 --src_tar_weight 0.0 --consis_tar --box_warm_iter 1000 --bt 0.1 --consis_weight 0.0 --ext_weight 0.0 --res_weight 0.01 --align_mode 1 --ext_mode 0 --seed 8 --amp --use_weight_pred --weight_tau 1.0 --port 15611 --ot_alpha 1.0 --ot_beta 0.5 --ot_gamma 0.5 --word2vec_path 'GoogleNews-vectors-negative300.bin' 2>&1 | tee ./domainnet_ot_real.log


# srun --partition=cse-gpu-all --nodelist=dgx-v100-01 --gres=gpu:2 python3 main.py --name 'DomainNet' --src 'quickdraw' 'infograph' 'real' 'clipart' 'sketch' --tar 'painting'  --batch-size 32 --backbone 'resnet101' --warmup-steps 0 --student-wait-steps 0 --eval-step 750 --wait_step 1500 --bottleneck 'linear' --total-steps 50001 --num-classes 345 --tar_weight 1.0 --tar_threshold 0.6 --tar_alignment_weight 0.7 --src_tar_weight 0.0 --consis_tar --box_warm_iter 1000 --bt 0.1 --consis_weight 0.0 --ext_weight 0.0 --res_weight 0.01 --align_mode 1 --ext_mode 0 --seed 8 --amp --use_weight_pred --weight_tau 1.0  --port 15600 --ot_alpha 1.0 --ot_beta 0.5 --ot_gamma 0.5 --word2vec_path 'GoogleNews-vectors-negative300.bin' 2>&1 | tee ./domainnet_ot_painting.log

# srun --partition=cse-gpu-all --nodelist=dgx-v100-01 --gres=gpu:2 python3 main.py --name 'DomainNet' --src 'quickdraw' 'painting' 'real' 'clipart' 'sketch' --tar 'infograph'  --batch-size 32 --backbone 'resnet101' --warmup-steps 0 --student-wait-steps 0 --eval-step 750 --wait_step 1500 --bottleneck 'linear' --total-steps 40001 --num-classes 345 --tar_weight 1.0 --tar_threshold 0.6 --tar_alignment_weight 0.7 --src_tar_weight 0.0 --consis_tar --box_warm_iter 1000 --bt 0.1 --consis_weight 0.0 --ext_weight 0.0 --res_weight 0.01 --align_mode 1 --ext_mode 0 --seed 8 --amp --use_weight_pred --weight_tau 1.0 --port 15666 --ot_alpha 1.0 --ot_beta 0.5 --ot_gamma 0.5 --word2vec_path 'GoogleNews-vectors-negative300.bin' 2>&1 | tee ./domainnet_ot_infograph.log

#                                                                   python3 nov.py --name 'officehome' --src 'Product' 'Clipart' 'Art' --tar 'Real_World' --batch-size 32 --warmup-steps 0 --student-wait-steps 0 --wait_step 100 --bottleneck 'linear' --total-steps 10001 --num-classes 65 --tar_weight 1.5 --tar_threshold 0.9 --tar_alignment_weight 0.5 --src_tar_weight 0.0 --consis_tar --consis_weight 0.0 --ext_weight 0.0 --res_weight 0.01 --align_mode 1 --ext_mode 0 --seed 8 --amp --use_weight_pred --weight_tau 1.0 --port 15339 --grad-clip 10.0 > ./apr-r_new.log 2>&1

# srun --partition=cse-gpu-all --nodelist=dgx-a100-02 --gres=gpu:1 python3 main.py --name 'officehome' --src 'Art' 'Product' 'Real_World' --tar 'Clipart' --batch-size 32 --warmup-steps 0 --student-wait-steps 0 --wait_step 100 --bottleneck 'linear' --total-steps 10001 --num-classes 65 --tar_weight 1.5 --tar_threshold 0.9 --tar_alignment_weight 0.5 --src_tar_weight 0.0 --consis_tar --consis_weight 0.0 --ext_weight 0.0 --res_weight 0.01 --align_mode 1 --ext_mode 0 --seed 8 --amp --use_weight_pred --weight_tau 1.0 --port 15361 --grad-clip 10.0 --ot_alpha 1.0 --ot_beta 0.5 --ot_gamma 0.5 --word2vec_path 'GoogleNews-vectors-negative300.bin' 2>&1 | tee ./officehome_ot_cmmd_clipart.log

# srun --partition=cse-gpu-all --nodelist=dgx-a100-02 --gres=gpu:1 python3 main-ot-sh.py --name 'officehome' --src 'Art' 'Product' 'Real_World' --tar 'Clipart' --batch-size 32 --warmup-steps 0 --student-wait-steps 0 --wait_step 100 --bottleneck 'linear' --total-steps 10001 --num-classes 65 --tar_weight 1.5 --tar_threshold 0.9 --tar_alignment_weight 0.01 --src_tar_weight 0.0 --consis_tar --consis_weight 0.0 --ext_weight 0.0 --res_weight 0.01 --align_mode 1 --ext_mode 0 --seed 8 --amp --use_weight_pred --weight_tau 1.0 --port 15380 --grad-clip 10.0 --ot_alpha 1.0 --ot_beta 0.5 --ot_gamma 0.5 --word2vec_path 'GoogleNews-vectors-negative300.bin' --gamma_explore 1.0 --gamma_mid 0.0 --gamma_refine -0.5 2>&1 | tee ./officehome_ot_sh_clipart.log

# srun --partition=cse-gpu-all --nodelist=dgx-a100-02 --gres=gpu:1 python3 main-ot-sh.py --name 'officehome' --src 'Art' 'Product' 'Clipart' --tar 'Real_World' --batch-size 32 --warmup-steps 0 --student-wait-steps 0 --wait_step 100 --bottleneck 'linear' --total-steps 10001 --num-classes 65 --tar_weight 1.5 --tar_threshold 0.9 --tar_alignment_weight 0.01 --src_tar_weight 0.0 --consis_tar --consis_weight 0.0 --ext_weight 0.0 --res_weight 0.01 --align_mode 1 --ext_mode 0 --seed 8 --amp --use_weight_pred --weight_tau 1.0 --port 15381 --grad-clip 10.0 --ot_alpha 1.0 --ot_beta 0.5 --ot_gamma 0.5 --word2vec_path 'GoogleNews-vectors-negative300.bin' --gamma_explore 1.0 --gamma_mid 0.0 --gamma_refine -0.5 2>&1 | tee ./officehome_ot_sh_realworld.log

# srun --partition=cse-gpu-all --nodelist=cse-node009 --gres=gpu:1 python3 main-ot-sh.py --name 'officehome' --src 'Art' 'Real_World' 'Clipart' --tar 'Product' --batch-size 32 --warmup-steps 0 --student-wait-steps 0 --wait_step 100 --bottleneck 'linear' --total-steps 10001 --num-classes 65 --tar_weight 1.5 --tar_threshold 0.9 --tar_alignment_weight 0.01 --src_tar_weight 0.0 --consis_tar --consis_weight 0.0 --ext_weight 0.0 --res_weight 0.01 --align_mode 1 --ext_mode 0 --seed 8 --amp --use_weight_pred --weight_tau 1.0 --port 15382 --grad-clip 10.0 --ot_alpha 1.0 --ot_beta 0.5 --ot_gamma 0.5 --word2vec_path 'GoogleNews-vectors-negative300.bin' --gamma_explore 1.0 --gamma_mid 0.0 --gamma_refine -0.5 2>&1 | tee ./officehome_ot_sh_product.log


# srun --partition=cse-gpu-all --nodelist=dgx-a100-02 --gres=gpu:1 python3 main-better.py --name 'officehome' --src 'Art' 'Clipart' 'Real_World' --tar 'Product' --batch-size 32 --warmup-steps 0 --student-wait-steps 0 --wait_step 100 --bottleneck 'linear' --total-steps 10001 --num-classes 65 --tar_weight 1.5 --tar_threshold 0.9 --tar_alignment_weight 0.5 --src_tar_weight 0.0 --consis_tar --consis_weight 0.0 --ext_weight 0.0 --res_weight 0.01 --align_mode 1 --ext_mode 0 --seed 8 --amp --use_weight_pred --weight_tau 1.0 --port 15380 --grad-clip 10.0 --ot_alpha 1.0 --ot_beta 0.5 --ot_gamma 0.5 --word2vec_path 'GoogleNews-vectors-negative300.bin' --gamma_explore 0.5 --gamma_mid 0.5 --gamma_refine 0.5 --log_file_name ./logs/officehome-product-loss.log 2>&1 | tee ./officehome_loss_product.log

# srun --partition=cse-gpu-all --nodelist=dgx-a100-02 --gres=gpu:1 python3 main-better.py --name 'officehome' --src 'Product' 'Clipart' 'Real_World' --tar 'Art' --batch-size 32 --warmup-steps 0 --student-wait-steps 0 --wait_step 100 --bottleneck 'linear' --total-steps 10001 --num-classes 65 --tar_weight 1.5 --tar_threshold 0.9 --tar_alignment_weight 0.5 --src_tar_weight 0.0 --consis_tar --consis_weight 0.0 --ext_weight 0.0 --res_weight 0.01 --align_mode 1 --ext_mode 0 --seed 8 --amp --use_weight_pred --weight_tau 1.0 --port 15381 --grad-clip 10.0 --ot_alpha 1.0 --ot_beta 0.5 --ot_gamma 0.5 --word2vec_path 'GoogleNews-vectors-negative300.bin' --gamma_explore 0.5 --gamma_mid 0.5 --gamma_refine 0.5 2>&1 | tee ./officehome_ot_loss_art.log

# srun --partition=cse-gpu-all --nodelist=dgx-a100-02 --gres=gpu:1 python3 main-better.py --name 'officehome' --src 'Art' 'Clipart' 'Product' --tar 'Real_World' --batch-size 32 --warmup-steps 0 --student-wait-steps 0 --wait_step 100 --bottleneck 'linear' --total-steps 10001 --num-classes 65 --tar_weight 1.5 --tar_threshold 0.9 --tar_alignment_weight 0.5 --src_tar_weight 0.0 --consis_tar --consis_weight 0.0 --ext_weight 0.0 --res_weight 0.01 --align_mode 1 --ext_mode 0 --seed 8 --amp --use_weight_pred --weight_tau 1.0 --port 15382 --grad-clip 10.0 --ot_alpha 1.0 --ot_beta 0.5 --ot_gamma 0.5 --word2vec_path 'GoogleNews-vectors-negative300.bin' --gamma_explore 0.5 --gamma_mid 0.5 --gamma_refine 0.5 2>&1 | tee ./officehome_ot_loss_realworld.log 

# srun --partition=cse-gpu-all --nodelist=dgx-a100-02 --gres=gpu:1 python3 main-better.py --name 'officehome' --src 'Art' 'Product' 'Real_World' --tar 'Clipart' --batch-size 32 --warmup-steps 0 --student-wait-steps 0 --wait_step 100 --bottleneck 'linear' --total-steps 10001 --num-classes 65 --tar_weight 1.5 --tar_threshold 0.9 --tar_alignment_weight 0.5 --src_tar_weight 0.0 --consis_tar --consis_weight 0.0 --ext_weight 0.0 --res_weight 0.01 --align_mode 1 --ext_mode 0 --seed 8 --amp --use_weight_pred --weight_tau 1.0 --port 15383 --grad-clip 10.0 --ot_alpha 1.0 --ot_beta 0.5 --ot_gamma 0.5 --word2vec_path 'GoogleNews-vectors-negative300.bin' --gamma_explore 0.5 --gamma_mid 0.5 --gamma_refine 0.5 2>&1 | tee ./officehome_ot_loss_clipart.log


srun --partition=cse-gpu-all --nodelist=cse-node010 --gres=gpu:2 python3 main-ot-sh.py --name 'DomainNet' --src 'painting' 'infograph' 'real' 'clipart' 'sketch' --tar 'quickdraw'  --batch-size 32 --backbone 'resnet101' --warmup-steps 0 --student-wait-steps 0 --eval-step 750 --wait_step 4000 --bottleneck 'linear' --total-steps 30001 --num-classes 345 --tar_weight 1.0 --tar_threshold 0.6 --tar_alignment_weight 0.7 --src_tar_weight 0.0 --consis_tar --box_warm_iter 1000 --bt 0.1 --consis_weight 0.0 --ext_weight 0.0 --res_weight 0.01 --align_mode 1 --ext_mode 0 --seed 8 --amp --use_weight_pred --weight_tau 1.0 --port 15611 --grad-clip 10.0 --ot_alpha 1.0 --ot_beta 0.5 --ot_gamma 0.5 --word2vec_path 'GoogleNews-vectors-negative300.bin' --gamma_explore 0.5 --gamma_mid 0.5 --gamma_refine 0.5 --log_file_name ./logs/domainnet-quickdraw-new-loss.log 2>&1 | tee ./domainnet-new-loss-quickdraw.log

srun --partition=cse-gpu-all --nodelist=cse-node011 --gres=gpu:2 python3 main-ot-sh.py --name 'DomainNet' --src 'quickdraw' 'infograph' 'painting' 'real' 'clipart' --tar 'sketch'  --batch-size 32 --backbone 'resnet101' --warmup-steps 0 --student-wait-steps 0 --eval-step 750 --wait_step 1500 --bottleneck 'linear' --total-steps 40001 --num-classes 345 --tar_weight 1.0 --tar_threshold 0.6 --tar_alignment_weight 0.7 --src_tar_weight 0.0 --consis_tar --box_warm_iter 1000 --bt 0.1 --consis_weight 0.0 --ext_weight 0.0 --res_weight 0.01 --align_mode 1 --ext_mode 0 --seed 8 --amp --use_weight_pred --weight_tau 1.0  --port 15614 --grad-clip 10.0 --ot_alpha 1.0 --ot_beta 0.5 --ot_gamma 0.5 --word2vec_path 'GoogleNews-vectors-negative300.bin' --gamma_explore 0.5 --gamma_mid 0.5 --gamma_refine 0.5 --log_file_name ./logs/domainnet-sketch-new-loss-csenode.log 2>&1 | tee ./domainnet-new-loss-sketch-csenode.log
